### ISSUE TITLE
Namespace operator needs to be created in cpd-operators namespace

### ISSUE THREAD

**Issue by spansare** [cloud-native-toolkit/terraform-gitops-cp4d-operator#16]
As per link : https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=tasks-creating-operator-subscriptions in Step 3.3

**Comment by balasgit** [comment]
Does it fix the issue ? @spansare

**Comment by sgumpana** [comment]
Fixed and released in PR -  https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator/pull/18
