### ISSUE TITLE
Incorrect Catalog Sources for CPD

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/terraform-gitops-cp4d-operator#17]
As per CPD documentation (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=ccs-creating-catalog-sources-that-automatically-pull-latest-images-from-entitled-registry) the below catalog sources are required.
1. ibm-operator-catalog
2.  ibm-db2uoperator-catalog

But in [terraform-gitops-cp4d-operator](https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator/blob/main/charts/ibm-cp4d/templates/cpd_catalogsources.yaml) many catalog sources are created which are not required. ibm-operator-catalog alone will takecare of all catalog sources

**Comment by balasgit** [comment]
Is the fix address the issues ?

**Comment by sgumpana** [comment]
Fixed and released in PR -  https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator/pull/18
